### ISSUE TITLE
associate_sewers.py - Handle uniqs tuple error

### ISSUE THREAD

**Issue by nworbc5565** [aerispaha/sewerstudies#2]
[associate_sewers.txt](https://github.com/aerispaha/sewerstudies/files/821743/associate_sewers.txt)

![associate_sewers_error](https://cloud.githubusercontent.com/assets/22076991/23618916/f46a4c82-025f-11e7-8d5f-73145a118c1c.JPG)

Modification to error message should be handled so that study sewer records where StudyArea_ID = 'None' are identified, and an error message will indicate that a study sewer has not been assigned a StudyArea_ID.

**Comment by aerispaha** [comment]
This has been taken care of and pushed to the production environment. Users will now see a warning "Sewer in StudiedSewers where StudyArea_ID is Null!" when there is a sewer with None types in bad places.
